### ISSUE TITLE
wsgi.errors: str object has no attribute write

### ISSUE THREAD

**Issue by vectart** [webpy/webpy#16]
Today I'm update my Debian server and got the error:

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/web/wsgiserver/__init__.py", line 1174, in communicate
    req.respond()
  File "/usr/lib/pymodules/python2.6/web/wsgiserver/__init__.py", line 544, in respond
    self._respond()
  File "/usr/lib/pymodules/python2.6/web/wsgiserver/__init__.py", line 556, in _respond
    response = self.wsgi_app(self.environ, self.start_response)
  File "/usr/lib/pymodules/python2.6/web/httpserver.py", line 237, in __call__
    return self.app(environ, xstart_response)
  File "/usr/lib/pymodules/python2.6/web/httpserver.py", line 212, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/pymodules/python2.6/web/httpserver.py", line 237, in __call__
    return self.app(environ, xstart_response)
  File "/usr/lib/pymodules/python2.6/web/application.py", line 293, in wsgi
    start_resp(status, headers)
  File "/usr/lib/pymodules/python2.6/web/httpserver.py", line 233, in xstart_response
    out = start_response(status, response_headers, *args)
  File "/usr/lib/pymodules/python2.6/web/httpserver.py", line 234, in xstart_response
    self.log(status, environ)
  File "/usr/lib/pymodules/python2.6/web/httpserver.py", line 251, in log
    print >> outfile, utils.safestr(msg)
AttributeError: 'str' object has no attribute 'write'
```

It's just when I run application.
When I'm use request emulation, it's okay.

**Comment by iredmail** [comment]
No plan to fix this due to no sample code snippet to reproduce the issue.
Feel free to reopen this issue if it's required.
