### ISSUE TITLE
GBK UTF-8 error

### ISSUE THREAD

**Issue by marswj** [webpy/webpy#197]
web.py 使用cx_freeze打包后，作为客户端软件，运行在windows中，在有中文的目录中运行时，后台出现错误

google translate：
web.py use cx_freeze package, as the client software running in windows, run in the directory is a Chinese background error

log：

Traceback (most recent call last):
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\application.
py", line 237, in process
    return p(lambda: process(processors))
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\application.
py", line 566, in processor
    return handler()
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\application.
py", line 237, in <lambda>
    return p(lambda: process(processors))
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\application.
py", line 246, in process
    raise self.internalerror()
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\application.
py", line 478, in internalerror
    return debugerror.debugerror()
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\debugerror.p
y", line 305, in debugerror
    return web._InternalError(djangoerror())
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\debugerror.p
y", line 295, in djangoerror
    return t(exception_type, exception_value, frames)
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\template.py"
, line 881, in __call__
    return BaseTemplate.**call**(self, _a, *_kw)
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\template.py"
, line 808, in **call**
    return self.t(_a, *_kw)
  File "F:\temp\新建文件夹\dist\TFjxc.exe\web\debugerror.pyc", line 153, in **te
mplate**
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\template.py"
, line 825, in _escape
    value = safeunicode(value)
  File "D:\dev\Python27\lib\site-packages\web.py-0.37-py2.7.egg\web\utils.py", l
ine 348, in safeunicode
    return obj.decode(encoding)
  File "C:\Python\32-bit\2.7\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 8: invalid c
ontinuation byte

**Comment by userlerueda** [comment]
Is this still a problem or was it related to character encoding and may now be closed?

**Comment by jzellman** [comment]
It could still be a problem but it hasn't been talked about in 4 years and there is little information to go on. @anandology close this due to lack of info and outdated?
