### ISSUE TITLE
when i run blog example code of webpy, i encounter a bug

### ISSUE THREAD

**Issue by batmancn** [webpy/webpy#341]
i run blog example code, http://webpy.org/src/blog/0.3, i encounter a bug as bellow :

My webpy version is :
root@iZ287xcvr93Z:~# aptitude show python-webpy
Package: python-webpy  
State: installed
Automatically installed: no
Version: 1:0.37+20120626-1

My ubuntu version is 12.04

This is the call trace from web:
Traceback (innermost first)

/usr/lib/python2.7/dist-packages/web/utils.py in datestr
    if type(now).**name** == "DateTime":
        now = datetime.datetime.fromtimestamp(now)
    if type(then).**name** == "DateTime":
        then = datetime.datetime.fromtimestamp(then)
    elif type(then).**name** == "date":
        then = datetime.datetime(then.year, then.month, then.day)
    delta = now - then ...
    deltaseconds = int(delta.days \* oneday + delta.seconds + delta.microseconds \* 1e-06)
    deltadays = abs(deltaseconds) // oneday
    if deltaseconds < 0: deltadays *= -1 # fix for oddity of floor
    if deltadays:
        if abs(deltadays) < 4:
▶ Local vars
templates/index.html in **template**

h1>Blog posts</h1>

<ul>
$for post in posts:
    <li>
        <a href="/view/$post.id">$post.title</a> 
        from $datestr(post.posted_on) 
 ...
        <a href="/edit/$post.id">Edit</a>
    </li>
</ul>

▶ Local vars
/usr/lib/python2.7/dist-packages/web/template.py in template
                return self._base(t(_a, *_kw)) ...
▶ Local vars
/root/BasicBlog/blog.py in GET
        return render.index(posts) ...
▶ Local vars
/usr/lib/python2.7/dist-packages/web/application.py in handle_class
            return tocall(*args) ...
▶ Local vars
/usr/lib/python2.7/dist-packages/web/application.py in _delegate
            return handle_class(cls) ...
▶ Local vars
/usr/lib/python2.7/dist-packages/web/application.py in handle
        return self._delegate(fn, self.fvars, args) ...
▶ Local vars
/usr/lib/python2.7/dist-packages/web/application.py in process
                    return self.handle() ...
▶ Local vars

This is the call trace from python:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 396, in handle_class
    return tocall(_args)
  File "/root/BasicBlog/blog.py", line 28, in GET
    return render.index(posts)
  File "/usr/lib/python2.7/dist-packages/web/template.py", line 1020, in template
    return self._base(t(_a, **kw))
  File "/usr/lib/python2.7/dist-packages/web/template.py", line 881, in __call__
    return BaseTemplate.**call**(self, _a, *_kw)
  File "/usr/lib/python2.7/dist-packages/web/template.py", line 808, in **call**
    return self.t(_a, *_kw)
  File "templates/index.html", line 13, in **template**
  File "/usr/lib/python2.7/dist-packages/web/utils.py", line 905, in datestr
    delta = now - then
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'unicode'

Does any one know the root cause? thx

**Comment by batmancn** [comment]
Sorry for the poor format in last mail.

I think this is important:
File "templates/index.html", line 13, in template
File "/usr/lib/python2.7/dist-packages/web/utils.py", line 905, in datestr
delta = now - then
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'unicode'

And the templates/index.html is 
$def with (posts)
<h1>Blog posts</h1>
<ul>
$for post in posts:
    <li>
        <a href="/view/$post.id">$post.title</a> 
        from $datestr(post.posted_on) 
        <a href="/edit/$post.id">Edit</a>
    </li>
</ul>

The post.posted_on is value from sqlite3(This is define by me), its schema is same as source code:
CREATE TABLE entries (
    id INT AUTO_INCREMENT,
    title TEXT,
    content TEXT,
    posted_on DATETIME,
    primary key (id)
);

I don't know what's difference between mysql and sqlite3 in DATETIME

**Comment by batmancn** [comment]
From http://www.th7.cn/Program/Python/201301/119905.shtml
We could see this is caused by difference of mysql and sqlite.
So we have to change the format of data from sqlite3 database of DATETIME type.
