### ISSUE TITLE
webapp crashes when unicode text is returned as response

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#371]
Code to reproduce the bug is available at

https://gist.github.com/anandology/72168ffbf33e87ebcfb419d12fd5e7cd

It crashes with the following error.

	UnicodeEncodeError('latin-1', '\u0c05\u0c06', 0, 2, 'ordinal not in range(256)')
	Traceback (most recent call last):
	  File "/Users/anand/github/webpy/webpy/web/wsgiserver/wsgiserver3.py", line 1089, in communicate
	    req.respond()
	  File "/Users/anand/github/webpy/webpy/web/wsgiserver/wsgiserver3.py", line 877, in respond
	    self.server.gateway(self).respond()
	  File "/Users/anand/github/webpy/webpy/web/wsgiserver/wsgiserver3.py", line 1991, in respond
	    chunk = chunk.encode('ISO-8859-1')
	UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)

cc: @Zashas

**Comment by anandology** [comment]
I think it is caused because `str` is returned from the wsgiapp. I think it should send only `bytes`. The conversion from `str` to `bytes` should happen in `web.py`, not in `wsgiserver`.

**Comment by Zashas** [comment]
I'll submit a patch tomorrow.
