### ISSUE TITLE
编码

### ISSUE THREAD

**Issue by xlh001** [webpy/webpy#414]
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 257, in process
    return self.handle()
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 488, in _delegate
    return handle_class(cls)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 466, in handle_class
    return tocall(*args)
  File "C:\Users\Administrator\Desktop\python\网站开发\3-21素材\main.py", line 2
8, in GET
    return render.index()
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\template.py", line 1034, in __getattr__
    t = self._template(name)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\template.py", line 1031, in _template
    return self._load_template(name)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\template.py", line 1016, in _load_template
    return Template(open(path).read(), filename=path, **self._keywords)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 156: illegal
multibyte sequence

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 257, in process
    return self.handle()
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 488, in _delegate
    return handle_class(cls)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 466, in handle_class
    return tocall(*args)
  File "C:\Users\Administrator\Desktop\python\网站开发\3-21素材\main.py", line 2
8, in GET
    return render.index()
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\template.py", line 1034, in __getattr__
    t = self._template(name)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\template.py", line 1031, in _template
    return self._load_template(name)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\template.py", line 1016, in _load_template
    return Template(open(path).read(), filename=path, **self._keywords)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 156: illegal
multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 255, in process
    return p(lambda: process(processors))
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 643, in processor
    return handler()
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 255, in <lambda>
    return p(lambda: process(processors))
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 264, in process
    raise self.internalerror()
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\application.py", line 545, in internalerror
    return debugerror()
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\debugerror.py", line 313, in debugerror
    return web._InternalError(djangoerror())
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\debugerror.py", line 271, in djangoerror
    _get_lines_from_file(filename, lineno, 7)
  File "D:\Program Files\Python36\lib\site-packages\web.py-0.40.dev0-py3.6.egg\w
eb\debugerror.py", line 246, in _get_lines_from_file
    source = open(filename).readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8d in position 135: illegal
multibyte sequence

192.168.2.1:17075 - - [23/Mar/2017 10:22:52] "HTTP/1.1 GET /" - 500 Internal Ser
ver Error

**Comment by anandology** [comment]
What is the version of web.py that you are using?

**Comment by XLHtest** [comment]
python3.6 Windows7x64 web.py-0.40.dev0-py3.6.egg

**Comment by buckle2000** [comment]
你应该用utf-8而不是gbk

**Comment by buckle2000** [comment]
你应该用utf-8而不是gbk

**Comment by iredmail** [comment]
Not a webpy issue.
