### ISSUE TITLE
python3.6 cannot install webpy

### ISSUE THREAD

**Issue by Z644912187** [webpy/webpy#428]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1j/9ln5m3n97yj8rzwk_dsph4pm0000gn/T/pip-build-fncsc_0f/web.py/setup.py", line 6, in <module>
        from web import __version__
      File "/private/var/folders/1j/9ln5m3n97yj8rzwk_dsph4pm0000gn/T/pip-build-fncsc_0f/web.py/web/__init__.py", line 14, in <module>
        import utils, db, net, wsgi, http, webapi, httpserver, debugerror
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/db/__init__.py", line 69
        print "var", var
                  ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by jzellman** [comment]
Try dev version:
    pip install web.py==0.40.dev0
