### ISSUE TITLE
WindowsError: [Error 6] The handle is invalid.

### ISSUE THREAD

**Issue by pike-msonda** [webpy/webpy#457]
I am using pyinstaller-3.3.1 to freeze the webpy (0.39) application that I am working on.  When I run the exe, the returned error is:
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "code.py", line 41, in <module>
  File "site-packages\web\application.py", line 313, in run
  File "site-packages\web\wsgi.py", line 59, in runwsgi
  File "site-packages\web\httpserver.py", line 157, in runsimple
  File "site-packages\web\wsgiserver\__init__.py", line 1745, in start
  File "site-packages\web\wsgiserver\__init__.py", line 1776, in bind
  File "site-packages\web\wsgiserver\__init__.py", line 1508, in prevent_socket_inheritance
WindowsError: [Error 6] The handle is invalid.

As shown in the traceback output, the problem seems to be coming form the function: 
```
   def prevent_socket_inheritance(sock):
         """Mark the given socket fd as non-inheritable (Windows)."""
                 if not windll.kernel32.SetHandleInformation(sock.fileno(), 1, 0):
                        raise WinError()
```

What am I doing wrong?

**Comment by iredmail** [comment]
Hi @pike-msonda 

Could you please try again with the latest git version of web.py? It should fix this issue.

**Comment by iredmail** [comment]
Closed due to no further update.
