### ISSUE TITLE
TypeError('WSGI response header value 469 is not of type str.',)

### ISSUE THREAD

**Issue by darxboy** [webpy/webpy#495]
i face some issue that endurance me for couple day. i hope someone will help me to release these bug.. thanx
/usr/bin/python3.5 /home/dido/PycharmProjects/CodeWizard/Controller.py
http://0.0.0.0:8080/

TypeError('WSGI response header value 469 is not of type str.',)
TypeError('WSGI response header value 469 is not of type str.',)
127.0.0.1:42642 - - [23/Jan/2019 14:20:24] "HTTP/1.1 GET /static/css/bootstrap-material-design.min.css" - 200 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1252, in communicate
    req.respond()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1056, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 144, in respond
    for chunk in filter(None, response):
  File "/usr/local/lib/python3.5/dist-packages/web.py-0.40.dev1-py3.5.egg/web/httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "/usr/local/lib/python3.5/dist-packages/web.py-0.40.dev1-py3.5.egg/web/httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 180, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1252, in communicate
    req.respond()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1056, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 144, in respond
    for chunk in filter(None, response):
  File "/usr/local/lib/python3.5/dist-packages/web.py-0.40.dev1-py3.5.egg/web/httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "/usr/local/lib/python3.5/dist-packages/web.py-0.40.dev1-py3.5.egg/web/httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 180, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
127.0.0.1:42640 - - [23/Jan/2019 14:20:25] "HTTP/1.1 GET /static/js/material.min.js" - 304 Not Modified
127.0.0.1:42640 - - [23/Jan/2019 14:20:25] "HTTP/1.1 GET /static/js/ripples.min.js" - 304 Not Modified
TypeError('WSGI response header value 469 is not of type str.',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1252, in communicate
    req.respond()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1056, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 144, in respond
    for chunk in filter(None, response):
  File "/usr/local/lib/python3.5/dist-packages/web.py-0.40.dev1-py3.5.egg/web/httpserver.py", line 234, in __iter__
    self.start_response(self.status, self.headers)
  File "/usr/local/lib/python3.5/dist-packages/web.py-0.40.dev1-py3.5.egg/web/httpserver.py", line 287, in xstart_response
    out = start_response(status, response_headers, *args)
  File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 180, in start_response
    'WSGI response header value %r is not of type str.' % v)
TypeError: WSGI response header value 469 is not of type str.
TypeError('WSGI response header value 469 is not of type str.',)
Traceback (most recent call last):

**Comment by iredmail** [comment]
Hi @darxboy,

Could you please try the latest git version of web.py? Reply here with related error if it doesn't work. We will try to fix it as soon as possible.

**Comment by iredmail** [comment]
Seems a py3 compatible issue, closed since it should be fixed with the latest git version which already have a lot py3 fixes.
