### ISSUE TITLE
Python 3 Write Error

### ISSUE THREAD

**Issue by tekram** [webpy/webpy#502]
The application atarts fine but gives the the below error:

2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]: Traceback (most recent call last):
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 255, in process
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return p(lambda: process(processors))
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 643, in processor
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return handler()
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 255, in <lambda>
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return p(lambda: process(processors))
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 264, in process
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     raise self.internalerror()
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 545, in internalerror
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return debugerror()
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/debugerror.py", line 313, in debugerror
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return web._InternalError(djangoerror())
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/debugerror.py", line 303, in djangoerror
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return t(exception_type, exception_value, frames)
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/template.py", line 904, in __call__
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return BaseTemplate.__call__(self, *a, **kw)
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/template.py", line 831, in __call__
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     return self.t(*a, **kw)
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/debugerror.py", line 193, in __template__
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     </div>
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/webapi.py", line 364, in input
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     out = rawinput(_method)
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/local/lib/python3.5/dist-packages/web/webapi.py", line 341, in rawinput
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     a = cgi.FieldStorage(fp=fp, environ=e, keep_blank_values=1)
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/lib/python3.5/cgi.py", line 561, in __init__
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     self.read_single()
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/lib/python3.5/cgi.py", line 740, in read_single
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     self.read_binary()
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:   File "/usr/lib/python3.5/cgi.py", line 762, in read_binary
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]:     self.file.write(data)
2019-07-03T19:19:29.216Z [labs.web.prod-web 4141d473de62]: TypeError: write() argument must be str, not bytes

**Comment by iredmail** [comment]
Could you please show ms sample code for reproducing this issue?

**Comment by tekram** [comment]
I think this may have been an issue in what I wrote. I am closing for now but if it occurs again, I will re-open. Thanks for your help.
