### ISSUE TITLE
debugerror not working

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#555]
debugerror doesn't seem to be broken now.

Here is what I've tried:

```
$ cat bad.py
import web

urls = (
    "/", "index"
)
app = web.application(urls, globals())

class index:
    def GET(self):
        raise Exception("foo")

if __name__ == "__main__":
    app.run()

$ python bad.py
http://0.0.0.0:8080/
```

When tried to access `http://0.0.0.0:8080/`, the dev server failed with the following error:

```
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "/Users/anand/github/webpy/webpy/web/application.py", line 289, in process
    return self.handle()
  File "/Users/anand/github/webpy/webpy/web/application.py", line 280, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/anand/github/webpy/webpy/web/application.py", line 530, in _delegate
    return handle_class(cls)
  File "/Users/anand/github/webpy/webpy/web/application.py", line 508, in handle_class
    return tocall(*args)
  File "/Users/anand/github/webpy/webpy/bad.py", line 10, in GET
    raise Exception("foo")
Exception: foo

Traceback (most recent call last):
  File "/Users/anand/github/webpy/webpy/web/application.py", line 289, in process
    return self.handle()
  File "/Users/anand/github/webpy/webpy/web/application.py", line 280, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/anand/github/webpy/webpy/web/application.py", line 530, in _delegate
    return handle_class(cls)
  File "/Users/anand/github/webpy/webpy/web/application.py", line 508, in handle_class
    return tocall(*args)
  File "/Users/anand/github/webpy/webpy/bad.py", line 10, in GET
    raise Exception("foo")
Exception: foo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anand/github/webpy/webpy/web/application.py", line 287, in process
    return p(lambda: process(processors))
  File "/Users/anand/github/webpy/webpy/web/application.py", line 699, in processor
    return handler()
  File "/Users/anand/github/webpy/webpy/web/application.py", line 287, in <lambda>
    return p(lambda: process(processors))
  File "/Users/anand/github/webpy/webpy/web/application.py", line 296, in process
    raise self.internalerror()
  File "/Users/anand/github/webpy/webpy/web/application.py", line 587, in internalerror
    return debugerror()
  File "/Users/anand/github/webpy/webpy/web/debugerror.py", line 333, in debugerror
    return web._InternalError(djangoerror())
  File "/Users/anand/github/webpy/webpy/web/debugerror.py", line 311, in djangoerror
    djangoerror_r = Template(djangoerror_t, filename=__file__, filter=websafe)
  File "/Users/anand/github/webpy/webpy/web/template.py", line 942, in __init__
    code = self.compile_template(text, filename)
  File "/Users/anand/github/webpy/webpy/web/template.py", line 1019, in compile_template
    compiled_code = compile(code, filename, "exec")
  File "/Users/anand/github/webpy/webpy/web/debugerror.py", line 8
    def with (exception_type, exception_value, frames)
           ^
SyntaxError: invalid syntax
```

Looks like something went wrong with templates.

**Comment by cclauss** [comment]
A Python keyword  cannot be used as a function name.
```
File "/Users/anand/github/webpy/webpy/web/debugerror.py", line 8
    def with (exception_type, exception_value, frames)
           ^
SyntaxError: invalid syntax
```
