### ISSUE TITLE
Backward compatibility problem at function 'db.select' while 'limit' keyword is used in webpy 0.40.

### ISSUE THREAD

**Issue by rrguardo** [webpy/webpy#570]
At **webpy 0.37** and earlier the select function allow use the limit keyword this way  limit='0, 10' 

```
web.py==0.37
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import web
>>> db = web.database(....)
>>> print db.select('users', limit='0, 10')
0.0 (1): SELECT * FROM users LIMIT 0, 10
<web.utils.IterBetter instance at 0x7fcc05fc5440>
```

But at **webpy 0.40** the select function don't allow use the limit keyword that way limit='0, 10' 
```
web.py==0.40
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import web
>>> db = web.database(...)
>>> print db.select('users', limit='0, 10')
ERR: SELECT * FROM users LIMIT '0, 10'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dcpt/venv/local/lib/python2.7/site-packages/web/db.py", line 884, in select
    return self.query(qout, processed=True)
  File "/home/dcpt/venv/local/lib/python2.7/site-packages/web/db.py", line 831, in query
    self._db_execute(db_cursor, sql_query)
  File "/home/dcpt/venv/local/lib/python2.7/site-packages/web/db.py", line 757, in _db_execute
    out = cur.execute(query, params)
  File "/home/dcpt/venv/local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 605, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/dcpt/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/dcpt/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/dcpt/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''0, 10'' at line 1")
```

All the web applications that use that keyword at select function in that way, now fail to run queries and require updates to use the new version 0.40

**Comment by iredmail** [comment]
Seems this commit on Feb 5, 2018 broke this:
https://github.com/webpy/webpy/commit/becbfb92d7601ddb0aededfdc9a91696bde2430f#diff-bab5d2282d3362e44ff9cea603fb052f

You should use `offset` with `limit`. for example, your code `select('users', limit='0, 10')` should be rewritten to:

```
db.select('users', offset=0, limit=10)
```
