### ISSUE TITLE
UnicodeEncodeError: I can't send header with "ğ"

### ISSUE THREAD

**Issue by Quiec** [webpy/webpy#590]
I cant send header with "ğ", "ğ" is utf8 character. 
My code:
<code>

        web.header('Charset','UTF-8')
        web.header('Content-Type', 'application/force-download; charset=utf-8', unique=True)
        web.header('Content-Disposition', 'attachment; filename=' + web.safestr("Duman - Kolay Değildir.flac"), unique=True)
        web.header('Content-Length', os.path.getsize("Duman - Kolay Değildir.flac"))
        return open("Duman - Kolay Değildir.flac", "rb").read()

</code>

Error:

> 
        UnicodeEncodeError('latin-1', 'attachment; filename=Duman - Kolay Değildir.flac', 37, 38, 'ordinal not in range(256)')
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/cheroot/server.py", line 1280, in communicate
            req.respond()
          File "/usr/local/lib/python3.6/dist-packages/cheroot/server.py", line 1083, in respond
    self.server.gateway(self).respond()
            File "/usr/local/lib/python3.6/dist-packages/cheroot/wsgi.py", line 143, in respond
              response = self.req.server.wsgi_app(self.env, self.start_response)
            File "/usr/local/lib/python3.6/dist-packages/web/httpserver.py", line 306, in __call__
              return self.app(environ, xstart_response)
            File "/usr/local/lib/python3.6/dist-packages/web/httpserver.py", line 273, in __call__
              return self.app(environ, start_response)
            File "/usr/local/lib/python3.6/dist-packages/web/application.py", line 351, in wsgi
              start_resp(status, headers)
            File "/usr/local/lib/python3.6/dist-packages/web/httpserver.py", line 302, in           xstart_response
              out = start_response(status, response_headers, *args)
            File "/usr/local/lib/python3.6/dist-packages/cheroot/wsgi.py", line 188, in start_response
              out_header = ntob(k), ntob(v)
            File "/usr/local/lib/python3.6/dist-packages/cheroot/_compat.py", line 36, in ntob
    return n.encode(encoding)
          UnicodeEncodeError: 'latin-1' codec can't encode character '\u011f' in position 37: ordinal not in range(256)

**Comment by cclauss** [comment]
Python 2 or Python 3 or both?

**Comment by Quiec** [comment]
Python 3.6

Christian Clauss <notifications@github.com>, 17 Oca 2020 Cum, 17:56
tarihinde şunu yazdı:

**Comment by iredmail** [comment]
Not a webpy issue/bug, you should encode the file name instead LIKE this:

```
...
name = 'Duman - Kolay Değildir.flac'
...

class ...:
    def GET(self):
        ...
        web.header('Content-Disposition', "attachment; filename=utf-8'en'" + str(name.encode("utf-8")), unique=True)
        ...
```
