### ISSUE TITLE
def with (exception_type, exception_value, frames) ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by regmiscacc** [webpy/webpy#630]
Here is my code.py:
import web
render = web.template.render('templates/')

urls = (
  '/', 'index'
)

class index:
  def GET(self):
    return render.index()

if __name__ == "__main__":
 app = web.application(urls, globals())
 app.run()

And here is my templates/index.html
`<em>Hello</em>, world!`

When i run it, i getting this error:
**Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1269, in communicate
    req.respond()
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1071, in respond
    self.server.gateway(self).respond()
  File "C:\Python38\lib\site-packages\cheroot\wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "C:\Python38\lib\site-packages\web\httpserver.py", line 306, in __call__
    return self.app(environ, xstart_response)
  File "C:\Python38\lib\site-packages\web\httpserver.py", line 273, in __call__
    return self.app(environ, start_response)
  File "C:\Python38\lib\site-packages\web\application.py", line 329, in wsgi
    result = self.handle_with_processors()
  File "C:\Python38\lib\site-packages\web\application.py", line 300, in handle_with_processors
    return process(self.processors)
  File "C:\Python38\lib\site-packages\web\application.py", line 297, in process
    raise self.internalerror()
  File "C:\Python38\lib\site-packages\web\application.py", line 588, in internalerror
    return debugerror()
  File "C:\Python38\lib\site-packages\web\debugerror.py", line 337, in debugerror
    return web._InternalError(djangoerror())
  File "C:\Python38\lib\site-packages\web\debugerror.py", line 315, in djangoerror
    djangoerror_r = Template(djangoerror_t, filename=__file__, filter=websafe)
  File "C:\Python38\lib\site-packages\web\template.py", line 943, in __init__
    code = self.compile_template(text, filename)
  File "C:\Python38\lib\site-packages\web\template.py", line 1020, in compile_template
    compiled_code = compile(code, filename, "exec")
  File "C:\Python38\lib\site-packages\web\debugerror.py", line 8
    def with (exception_type, exception_value, frames)
        ^
SyntaxError: invalid syntax**

Why?

**Comment by cclauss** [comment]
No semicolon at the end of the line???

**Comment by imbellish** [comment]
To clarify:
```
>>> print(r"""\$""")
\$
>>> print("""\
$""")
$
```

The built-in debug template itself no longer starts with a $ in this commit https://github.com/webpy/webpy/commit/e89daa8296ff858bbc37529143de372886ccc9c1#diff-8cb9990e42dd192c282402bb2016483dR38

**Comment by imbellish** [comment]
@cclauss what's your pull request process? I'm happy to contribute, simple fix.

**Comment by cclauss** [comment]
Pull requests gladly accepted and reviewed.  Our GitHub Actions-based continuous integration will run [pytest](https://github.com/webpy/webpy/blob/master/.github/workflows/lint_python.yml#L70) on all pull requests so we would also be delighted if you added tests.  Thx!

**Comment by cclauss** [comment]
Sorry...  I mistakenly pushed a solution directly to `master`.  Can you please retest your code against master and see if this problem continues to exist?  #631

**Comment by wdjwxh** [comment]
pip version is wrong.
so this issue shoue be handle asap.

**Comment by iredmail** [comment]
> pip version is wrong.

Wrong on which web page or document?

**Comment by cclauss** [comment]
On PyPI...  We need a new [release](https://github.com/webpy/webpy/releases) of master.

**Comment by cclauss** [comment]
@wdjwxh Can you please do `pip install -e git+https://github.com/webpy/webpy.git@master` and verify that the current code fixes this problem for your codebase?

**Comment by wdjwxh** [comment]
> @wdjwxh Can you please do `pip install -e git+https://github.com/webpy/webpy.git@master` and verify that the current code fixes this problem for your codebase?

It's works nice~, no problem

**Comment by lujoamel4** [comment]
`pip install -e git+https://github.com/webpy/webpy.git@master`
It does not work for me. Error message:
`Could not detect requirement name, please specify one with #egg=
`
When a new release is coming ? So I can install webpy from pip normally.

**Comment by iredmail** [comment]
@cclauss @anandology Should we release a new version? Any left issues/PRs?

**Comment by Max-Lumnar** [comment]
not working

**Comment by manutaberner** [comment]
> Here is my code.py:
> import web
> render = web.template.render('templates/')
> 
> urls = (
> '/', 'index'
> )
> 
> class index:
> def GET(self):
> return render.index()
> 
> if **name** == "**main**":
> app = web.application(urls, globals())
> app.run()
> 
> And here is my templates/index.html
> `<em>Hello</em>, world!`
> 
> When i run it, i getting this error:
> **Traceback (most recent call last): File "C:\Python38\lib\site-packages\cheroot\server.py", line 1269, in communicate req.respond() File "C:\Python38\lib\site-packages\cheroot\server.py", line 1071, in respond self.server.gateway(self).respond() File "C:\Python38\lib\site-packages\cheroot\wsgi.py", line 143, in respond response = self.req.server.wsgi_app(self.env, self.start_response) File "C:\Python38\lib\site-packages\web\httpserver.py", line 306, in **call** return self.app(environ, xstart_response) File "C:\Python38\lib\site-packages\web\httpserver.py", line 273, in **call** return self.app(environ, start_response) File "C:\Python38\lib\site-packages\web\application.py", line 329, in wsgi result = self.handle_with_processors() File "C:\Python38\lib\site-packages\web\application.py", line 300, in handle_with_processors return process(self.processors) File "C:\Python38\lib\site-packages\web\application.py", line 297, in process raise self.internalerror() File "C:\Python38\lib\site-packages\web\application.py", line 588, in internalerror return debugerror() File "C:\Python38\lib\site-packages\web\debugerror.py", line 337, in debugerror return web._InternalError(djangoerror()) File "C:\Python38\lib\site-packages\web\debugerror.py", line 315, in djangoerror djangoerror_r = Template(djangoerror_t, filename=**file**, filter=websafe) File "C:\Python38\lib\site-packages\web\template.py", line 943, in **init** code = self.compile_template(text, filename) File "C:\Python38\lib\site-packages\web\template.py", line 1020, in compile_template compiled_code = compile(code, filename, "exec") File "C:\Python38\lib\site-packages\web\debugerror.py", line 8 def with (exception_type, exception_value, frames) ^ SyntaxError: invalid syntax**
> 
> Why?

how did you solve it? I am having the same problem, once I try to use a template, it does not work...

**Comment by bpluly** [comment]
I have always created templates with...
`$def with(name)`
...as the first line. Obviously if there are objects that need passing for the template then they are the parameters, but I've always found that one was required.

The name doesn't need to be used in the template. I use the constant NAME in my main global file which has the name of app. And use it as...

```
      ```
def GET(self):
        name = NAME
        return render.index(name)
```
```

**Comment by cclauss** [comment]
I believe that this is fixed in the current releases.  Can you please retest on v0.6x and let us know if we can close this issue?

**Comment by 52lemon** [comment]
I got an error in running the up example(python3.8.3)

C:\Python38\python.exe D:/AmazingDo/Mytest/webpyApp.py
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "D:/AmazingDo/Mytest/webpyApp.py", line 19, in <module>
    app.run()
  File "C:\Python38\lib\site-packages\web\application.py", line 360, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "C:\Python38\lib\site-packages\web\wsgi.py", line 66, in runwsgi
    return httpserver.runsimple(func, server_addr)
  File "C:\Python38\lib\site-packages\web\httpserver.py", line 176, in runsimple
    server.start()
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1813, in start
    self.prepare()
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1763, in prepare
    self.bind(af, socktype, proto)
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1846, in bind
    sock = self.prepare_socket(
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1944, in prepare_socket
    connections.prevent_socket_inheritance(sock)
  File "C:\Python38\lib\site-packages\cheroot\connections.py", line 46, in prevent_socket_inheritance
    old_flags = fcntl.fcntl(fd, fcntl.F_GETFD)
AttributeError: module 'fcntl' has no attribute 'F_GETFD'

**Comment by cclauss** [comment]
This last commend has nothing to do with `def with`.

This issue is about https://docs.python.org/3/library/fcntl.html (which did have some changes in Python 3.8) and is code from https://github.com/cherrypy/cheroot so perhaps this issue should be opened on that repo.
* https://github.com/cherrypy/cheroot/blob/master/cheroot/connections.py#L46

**Comment by cclauss** [comment]
Do you have a file named `fcntl.py` somewhere on your system?
```
$ python3.8
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fcntl
>>> fcntl.F_GETFD
1
```

**Comment by 52lemon** [comment]
It's the problem of fcntl, not webpy.

**Comment by cclauss** [comment]
@regmiscacc Can this issue be closed?

**Comment by Max-Lumnar** [comment]
why close it while its still an issue? can it be fixed instead so we could install via pip as normal? would be awesome. Thanks for the hard work guys.
