### ISSUE TITLE
Def with SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by chicanosPsg** [webpy/webpy#641]
HI 
I made a simple code for learn WebPy , I have the latest version 0.51 but that not work  

------ file Controller -----
import web

urls = ('/', 'home')

render = web.template.render("Views/Templates", base = "MainLayout")
app = web.application(urls,globals())

#Clases/Routes

class home:
    def GET(self):
        return render.Home()

if __name__ == "__main__":
    app.run()

----- file MainLayout-------

$def with (page)

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CodeWizard</title>
</head>
<body>
    <div id="app">
        $:page
    </div>

</body>
</html>

------ File Home ------

<h1>Hello </h1>

____________errror------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\cheroot\server.py", line 1269, in communicate
    req.respond()
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\cheroot\server.py", line 1071, in respond
    self.server.gateway(self).respond()
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\cheroot\wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\httpserver.py", line 306, in __call__
    return self.app(environ, xstart_response)
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\httpserver.py", line 273, in __call__
    return self.app(environ, start_response)
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\application.py", line 329, in wsgi
    result = self.handle_with_processors()
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\application.py", line 300, in handle_with_processors
    return process(self.processors)
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\application.py", line 297, in process
    raise self.internalerror()
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\application.py", line 588, in internalerror
    return debugerror()
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\debugerror.py", line 337, in debugerror
    return web._InternalError(djangoerror())
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\debugerror.py", line 315, in djangoerror
    djangoerror_r = Template(djangoerror_t, filename=__file__, filter=websafe)
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\template.py", line 943, in __init__
    code = self.compile_template(text, filename)
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\template.py", line 1020, in compile_template
    compiled_code = compile(code, filename, "exec")
  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\debugerror.py", line 8
    def with (exception_type, exception_value, frames)
           ^
SyntaxError: invalid syntax

Template traceback:
    File 'C:\\Users\\VIVOBOOK\\PycharmProjects\\CodeWizard\\venv\\lib\\site-packages\\web\\debugerror.py', line 8
        http://www.xfree86.org/3.3.6/COPYRIGHT2.html#5

**Comment by cclauss** [comment]
https://github.com/webpy/webpy/issues/630#issuecomment-609574816

**Comment by chicanosPsg** [comment]
I install via the terminal pip install web.py==0.51

**Comment by cclauss** [comment]
Yes.  That is why it is not working.  Please try to pip install from master.

**Comment by chicanosPsg** [comment]
ok sorry for this stupid question but how you install from the master ?

**Comment by cclauss** [comment]
See the pip command under `#630 (comment)` above.

**Comment by chicanosPsg** [comment]
sorrry but missing something in my setup


(venv) C:\Users\VIVOBOOK\PycharmProjects\CodeWizard>pip install -e git+https://github.com/webpy/webpy.git@master
Could not detect requirement name for 'git+https://github.com/webpy/webpy.git@master', please specify one with #egg=your_package_name

**Comment by iredmail** [comment]
I don't have Windows OS for testing. :(

**Comment by chicanosPsg** [comment]
I have download the web folder from the master and replace the old file in my envirronement

now I have a new error :

  File "C:\Users\VIVOBOOK\PycharmProjects\CodeWizard\venv\lib\site-packages\web\template.py", line 1093, in _load_template
    raise AttributeError("No template named " + name)
AttributeError: No template named Home

**Comment by chicanosPsg** [comment]
I have found my error . it was a path problem ...
So evrything works 
Thx so lot
