### ISSUE TITLE
utils.py: name 'id' is not defined

### ISSUE THREAD

**Issue by lujoamel4** [webpy/webpy#647]
I'm porting a web application from python2 to python3. I'm try to running with Apache:

`Apache/2.4.29 (Ubuntu) mod_wsgi/4.5.17 Python/3.6 configured -- resuming normal operations`

Now I'm having this trouble:

```
File "/usr/local/lib/python3.6/dist-packages/web/utils.py", line 1316, in __hash__
NameError: name 'id' is not defined
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/web/utils.py", line 1313, in __del__
  File "/usr/local/lib/python3.6/dist-packages/web/utils.py", line 1316, in __hash__
NameError: name 'id' is not defined
```

It seems to be a bug in webpy, anyone has this issue?

**Comment by cclauss** [comment]
https://docs.python.org/3/library/functions.html#id
