### ISSUE TITLE
function db.multiple_insert will not work when items contain SQLLiternal object

### ISSUE THREAD

**Issue by cc-tse** [webpy/webpy#650]
when database supports_multiple_insert and run the below code:
```
       db.multiple_insert("caches", [{
            "cache_key": "0001",
            "createed_at": web.db.SQLLiteral("NOW()"),
        }])

```
error will be thrown:
```
ERR: INSERT INTO caches (cache_key, created_at) VALUES ('0001', <literal: 'NOW()'>)
Traceback (most recent call last):
  File "D:\Projects\DZApp\core\venv\lib\site-packages\mysql\connector\conversion.py", line 179, in to_mysql
    return getattr(self, "_{0}_to_mysql".format(type_name))(value)
AttributeError: 'MySQLConverter' object has no attribute '_sqlliteral_to_mysql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\DZApp\core\venv\lib\site-packages\mysql\connector\cursor.py", line 417, in _process_params
    res = [to_mysql(i) for i in res]
  File "D:\Projects\DZApp\core\venv\lib\site-packages\mysql\connector\cursor.py", line 417, in <listcomp>
    res = [to_mysql(i) for i in res]
  File "D:\Projects\DZApp\core\venv\lib\site-packages\mysql\connector\conversion.py", line 182, in to_mysql
    "MySQL type".format(type_name))
TypeError: Python 'sqlliteral' cannot be converted to a MySQL type
```

**Comment by iredmail** [comment]
The SQL statement generated by web.py seems correct:

```
>>> import web
>>> web.__version__
'0.51'
>>> db = web.DB(None, {})
>>> db.multiple_insert("caches", [{"createed_at": web.db.SQLLiteral("NOW()")}], _test=True)
[<sql: 'INSERT INTO caches (createed_at) VALUES (NOW())'>]
```

- Could you try above command on your server and show us the console output?
- Could you try SQL driver `pymysql` instead of `mysql-connector`, then test your own webpy app?

**Comment by cc-tse** [comment]
This problem occurs when db.supports_multiple_insert is True,  this will set to True when database driver is MySQL, may be PostgreSQL.
```
>>> import web
>>> web.__version__
'0.51'
>>> db = web.DB(None, {})
>>> db.supports_multiple_insert
False
>>> db.multiple_insert("caches", [{"created_at": web.db.SQLLiteral("NOW()")}], _test=True)
[<sql: 'INSERT INTO caches (created_at) VALUES (NOW())'>]

>>> # set db.supports_multiple_insert to True to reproduce the bug from here
>>> db.supports_multiple_insert = True
>>> db.multiple_insert("caches", [{"created_at": web.db.SQLLiteral("NOW()")}], _test=True)
<sql: "INSERT INTO caches (careated_at) VALUES (<literal: 'NOW()'>)">
```

**Comment by anandology** [comment]
Doesn't work for postgres too.

```
----> 1 db.multiple_insert("cache", [dict(key="test",
created_at=web.SQLLiteral("current_timestamp"))])

~/github/webpy/web/db.py in multiple_insert(self, tablename, values,
seqname, _test)
   1094             self._db_execute(db_cursor, q2)
   1095         else:
-> 1096             self._db_execute(db_cursor, sql_query)
   1097
   1098         try:

~/github/webpy/web/db.py in _db_execute(self, cur, sql_query)
    765             a = time.time()
    766             query, params = self._process_query(sql_query)
--> 767             out = cur.execute(query, params)
    768             b = time.time()
    769         except:

~/.venv/python37/lib/python3.7/site-packages/DBUtils/SteadyDB.py in
tough_method(*args, **kwargs)
    603                     self._setsizes()
    604                 method = getattr(self._cursor, name)
--> 605                 result = method(*args, **kwargs)  # try to execute
    606                 if execute:
    607                     self._clearsizes()
```

**Comment by anandology** [comment]
I think it would be better to document that `SQLLiteral` is not compatible with `multiple_insert` instead of trying to fix this. If we implement #657, it will not be possible to support `SQLLiteral` at all. 

@iredmail what do you think?

**Comment by iredmail** [comment]
I think we should take care of SQLLiteral with multiple_insert first. The usage seems quite common.

I was busy and didn’t dive into this issue yet, if you have some time please try to help fix it. :)

**Comment by anandology** [comment]
On Tue, Jul 21, 2020 at 4:20 PM iRedMail <notifications@github.com> wrote:

> I think we should take care of SQLLiteral with multiple_insert first. The
> usage seems quite common.
>
> I was busy and didn’t dive into this issue yet, if you have some time
> please try to help fix it. :)
>
The db driver doesn't support anything like sqlliteral, that is an
abstraction that web.py provides. It is possible to handle that when doing
regular queries we can add that as string to the query instead of a
parameter. However, when we are doing multiple insert, the db driver
expects the same number of parameters for each row, so it will not be
possible to support sqlliteral abstraction there.
