### ISSUE TITLE
Old cookie causes session to throw KeyError exception

### ISSUE THREAD

**Issue by UweSauter** [webpy/webpy#695]
The minimal working example attached at the end only works it the browser does not send a cookie from an older session when the app was restarted in-between.

The exception is:
```bash
[root@webpy minimal]# ./app.py
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/web/application.py", line 281, in process
    return p(lambda: process(processors))
  File "/usr/lib/python3.6/site-packages/web/session.py", line 100, in _processor
    self._load()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 116, in _load
    self._check_expiry()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 139, in _check_expiry
    return self.expired()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 210, in expired
    self._save()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 150, in _save
    del current_values["ip"]
KeyError: 'ip'
```
More detailed step-by-step description:
* I run the app using the EPEL for CentOS 8 provided python3-webpy package (0.61)
* I load the page in the browser (Firefox 82.0.3 in this case), log in and out
* I restart the app
* I reload the page
* The exception occurs and the browser shows `internal server error`
* I delete the cookie using the developer tools in Firefox
* I reload the page and the login form is show again
* This behavior occurs independent of the session storage back-end

I'm unsure if I'm doing something wrong here or if this is a bug in the session initialization code. As I have no control over the cookies present in a client's browser this situation needs to be handled on the server's side.

The username is `myuser`, the password is`mypassword`.

Minimal working example:
```python
#!/usr/bin/env python3
 
import web
 
web.config.debug = False
web.config.session_parameters['cookie_name'] = 'webpy_session_id'
web.config.session_parameters['cookie_domain'] = None
web.config.session_parameters['cookie_path'] = None
web.config.session_parameters['timeout'] = 600 # in seconds
web.config.session_parameters['ignore_expiry'] = False
web.config.session_parameters['ignore_change_ip'] = False
web.config.session_parameters['secret_key'] = 'aaaaaaaaaaaaaaaaa'
web.config.session_parameters['expired_message'] = 'Session expired'
 
urls = ('/', 'Index')
 
app = web.application(urls, globals())
## uncomment to use DiskStore
import tempfile
root = tempfile.mkdtemp()
store = web.session.DiskStore(root)
## uncomment to use MemoryStore
#store = web.session.MemoryStore()
 
session = web.session.Session(app, store, initializer={'authenticated': False})
 
class Index:
    def GET(self):
        authenticated = session.get('authenticated', None)
        if authenticated:
            body = f'''
<h3>Authentication status: {str(authenticated)}</h3><br/>
<form method="POST">
  <button id="action" name="action" value="logout">logout</button>
</form>
'''
        else:
            body = f'''
<h3>Authentication status: {str(authenticated)}</h3><br/>
<form method="POST">
  <table>
    <tbody>
      <tr>
        <th><label for="account">Account:</label></th>
        <td><input id="account" name="account" type="text"></td>
      </tr>
      <tr>
        <th><label for="password">Password:</label></th>
        <td><input id="password" name="password" type="password"></td>
      </tr>
      <tr>
        <th><label for="action"></label></th>
        <td><button id="action" name="action" value="login">login</button></td>
      </tr>
  </tbody>
</form>
'''
        return body
 
    def POST(self):
        inp = web.input()
        action = inp['action']
        if action == 'login':
            account = inp['account']
            password = inp['password']
# replace this section with a proper authentication/authorization method
            if account == "myuser":
                if password == "mypassword":
                    session['authenticated'] = True
                    return web.seeother('/')
                session['authenticated'] = False
                return 'Invalid password'
            session['authenticated'] = False
            return 'Invalid account'
# end simple authentication
        elif action == 'logout':
            session['authenticated'] = False
            web.seeother('/')
        else:
            return 'Unknown action'
 
if __name__ == '__main__':
    app.run()
```

**Comment by UweSauter** [comment]
I can also trigger this behavior if I insert a `session.kill()` in the logout branch of the example:
```python
        elif action == 'logout':
            session['authenticated'] = False
            session.kill()
            web.seeother('/')
```
Then, on logout, I get the same exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/web/application.py", line 281, in process
    return p(lambda: process(processors))
  File "/usr/lib/python3.6/site-packages/web/session.py", line 100, in _processor
    self._load()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 116, in _load
    self._check_expiry()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 139, in _check_expiry
    return self.expired()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 210, in expired
    self._save()
  File "/usr/lib/python3.6/site-packages/web/session.py", line 150, in _save
    del current_values["ip"]
KeyError: 'ip'
```

**Comment by iredmail** [comment]
Try this patch: https://github.com/webpy/webpy/pull/685

**Comment by UweSauter** [comment]
Thank you, that did the trick.
Two questions though:
* I can see that 0.62 does not yet contain this. Any idea when this will be released so I can trigger EPEL to provide the new version?
* Now, with included `session.kill()` I will get `Session expired` after logging out and refreshing doesn't bring back the login page. How to create a new session?
