### ISSUE TITLE
Python 3.12: tokenize.TokenError: ('unterminated string literal

### ISSUE THREAD

**Issue by scottbarnes** [webpy/webpy#784]
Due to a change in Python 3.12, the template engine appears no longer able to properly parse templates.

For example, on Open Library, trying to render _any_ template appears to result in:
```
(...snipped for brevity -- full context further down the issue)
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 318, in get_tokens
web-1           |     for t in tokenize.generate_tokens(readline):
web-1           |   File "/usr/local/lib/python3.12/tokenize.py", line 543, in _generate_tokens_from_c_tokenizer
web-1           |     raise TokenError(msg, (e.lineno, e.offset)) from None
web-1           | tokenize.TokenError: ('unterminated string literal (detected at line 1)', (1, 4))
```

The difference can bee seen as follows:
*Python 3.11.2*
```python
(venv311) 9c6e9bd7c219% python
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import web
>>> parser = web.template.Parser()
>>> parser.read_suite('<p><a href="$back">&larr; Back to Index</a></p>')
[<line: [t'<p><a href="', $back, t'">&larr; Back to Index</a></p>']>]
```

*Python 3.12.1*
```python
9c6e9bd7c219% python
Python 3.12.1 (main, Dec 19 2023, 03:09:45) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import web
>>> parser = web.template.Parser()
>>> parser.read_expr('<p><a href="$back">&larr; Back to Index</a></p>')
tokenize.TokenError: ('unterminated string literal (detected at line 1)', (1, 5))
```

Drilling down a bit one of the tokens, notably with an unmatched `"`, that is passed to `tokenize.generate_tokens()`:
*Python 3.11.2*
```python
In [11]: file = io.StringIO('$back">&larr; Back to Index</a></p>\n')

In [12]: for token in tokenize.generate_tokens(file.readline):
    ...:     print(token)
    ...: 
TokenInfo(type=60 (ERRORTOKEN), string='$', start=(1, 0), end=(1, 1), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='back', start=(1, 1), end=(1, 5), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=60 (ERRORTOKEN), string='"', start=(1, 5), end=(1, 6), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='>', start=(1, 6), end=(1, 7), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='&', start=(1, 7), end=(1, 8), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='larr', start=(1, 8), end=(1, 12), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string=';', start=(1, 12), end=(1, 13), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='Back', start=(1, 14), end=(1, 18), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='to', start=(1, 19), end=(1, 21), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='Index', start=(1, 22), end=(1, 27), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='<', start=(1, 27), end=(1, 28), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='/', start=(1, 28), end=(1, 29), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='a', start=(1, 29), end=(1, 30), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='>', start=(1, 30), end=(1, 31), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='<', start=(1, 31), end=(1, 32), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='/', start=(1, 32), end=(1, 33), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='p', start=(1, 33), end=(1, 34), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=54 (OP), string='>', start=(1, 34), end=(1, 35), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(1, 35), end=(1, 36), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=0 (ENDMARKER), string='', start=(2, 0), end=(2, 0), line='')
```

*Python 3.12.1*
```python
In [265]: file = io.StringIO('$back">&larr; Back to Index</a></p>\n')

In [266]: for token in tokenize.generate_tokens(file.readline):
     ...:     print(token)
     ...: 
TokenInfo(type=55 (OP), string='$', start=(1, 0), end=(1, 1), line='$back">&larr; Back to Index</a></p>\n')
TokenInfo(type=1 (NAME), string='back', start=(1, 1), end=(1, 5), line='$back">&larr; Back to Index</a></p>\n')
---------------------------------------------------------------------------
TokenError                                Traceback (most recent call last)
Cell In[266], line 1
----> 1 for token in tokenize.generate_tokens(file.readline):
      2     print(token)

File ~/.pyenv/versions/3.12.1/lib/python3.12/tokenize.py:543, in _generate_tokens_from_c_tokenizer(source, encoding, extra_tokens)
    541     raise e from None
    542 msg = _transform_msg(e.msg)
--> 543 raise TokenError(msg, (e.lineno, e.offset)) from None

TokenError: ('unterminated string literal (detected at line 1)', (1, 6))
```

It may not be significant, but whereas a lone `"` was formerly an `ERRORTOKEN`, now it's an `OP`. Either way, having an unmatched `"` seems to be a problem with `tokenize.generate_tokens()` now.

To the extent it is relevant, here are changes made to `tokenize` in Python 3.12: https://github.com/python/cpython/issues/111224#issuecomment-1776037598.

See also: internetarchive/openlibrary#8694

As promised, here's more context for the error:
```
web-1           | [2024-01-06 05:40:12 +0000] [10] [ERROR] Error handling request /
web-1           | Traceback (most recent call last):
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 136, in handle
web-1           |     self.handle_request(listener, req, client, addr)
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
web-1           |     respiter = self.wsgi(environ, resp.start_response)
web-1           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/httpserver.py", line 258, in __call__
web-1           |     return self.app(environ, start_response)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/openlibrary/openlibrary/core/middleware.py", line 46, in __call__
web-1           |     data = self.app(environ, new_start_response)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/openlibrary/scripts/openlibrary-server", line 129, in wrapper
web-1           |     return app(environ, start_response)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 315, in wsgi
web-1           |     result = self.handle_with_processors()
web-1           |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 286, in handle_with_processors
web-1           |     return process(self.processors)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 283, in process
web-1           |     raise self.internalerror()
web-1           |           ^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/openlibrary/openlibrary/plugins/openlibrary/code.py", line 942, in internalerror
web-1           |     name = save_error()
web-1           |            ^^^^^^^^^^^^
web-1           |   File "/openlibrary/openlibrary/plugins/openlibrary/code.py", line 931, in save_error
web-1           |     error = web.safestr(web.djangoerror())
web-1           |                         ^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/debugerror.py", line 307, in djangoerror
web-1           |     djangoerror_r = Template(djangoerror_t, filename=__file__, filter=websafe)
web-1           |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 932, in __init__
web-1           |     code = self.compile_template(text, filename)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 1003, in compile_template
web-1           |     code = Template.generate_code(
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 988, in generate_code
web-1           |     rootnode = parser.parse(text, filename)
web-1           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 87, in parse
web-1           |     suite = self.read_suite(text)
web-1           |             ^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 175, in read_suite
web-1           |     section, text = self.read_section(text)
web-1           |                     ^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 119, in read_section
web-1           |     return self.read_block_section(text2, begin_indent)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 477, in read_block_section
web-1           |     return self.create_block_node(keyword, stmt, block, begin_indent), text
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 481, in create_block_node
web-1           |     return self.statement_nodes[keyword](stmt, block, begin_indent)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 692, in __init__
web-1           |     BlockNode.__init__(self, *a, **kw)
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 626, in __init__
web-1           |     self.suite = Parser().read_suite(block)
web-1           |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 175, in read_suite
web-1           |     section, text = self.read_section(text)
web-1           |                     ^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 119, in read_section
web-1           |     return self.read_block_section(text2, begin_indent)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 477, in read_block_section
web-1           |     return self.create_block_node(keyword, stmt, block, begin_indent), text
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 481, in create_block_node
web-1           |     return self.statement_nodes[keyword](stmt, block, begin_indent)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 626, in __init__
web-1           |     self.suite = Parser().read_suite(block)
web-1           |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 175, in read_suite
web-1           |     section, text = self.read_section(text)
web-1           |                     ^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 126, in read_section
web-1           |     return self.readline(text)
web-1           |            ^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 198, in readline
web-1           |     node, line = self.read_node(line)
web-1           |                  ^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 224, in read_node
web-1           |     return self.read_expr(text, escape=escape)
web-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 362, in read_expr
web-1           |     simple_expr()
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 271, in simple_expr
web-1           |     extended_expr()
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 277, in extended_expr
web-1           |     lookahead = tokens.lookahead()
web-1           |                 ^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 338, in lookahead
web-1           |     self.items.append(self._next())
web-1           |                       ^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 343, in _next
web-1           |     return next(self.iteritems)
web-1           |            ^^^^^^^^^^^^^^^^^^^^
web-1           |   File "/home/openlibrary/.local/lib/python3.12/site-packages/web/template.py", line 318, in get_tokens
web-1           |     for t in tokenize.generate_tokens(readline):
web-1           |   File "/usr/local/lib/python3.12/tokenize.py", line 543, in _generate_tokens_from_c_tokenizer
web-1           |     raise TokenError(msg, (e.lineno, e.offset)) from None
web-1           | tokenize.TokenError: ('unterminated string literal (detected at line 1)', (1, 4))
```

**Comment by tfmorris** [comment]
Not very friendly of the Python folks to break 14 year old code, but given the big warning box at the top of 
https://docs.python.org/3/library/tokenize.html

<img width="816" alt="Screenshot 2024-01-10 at 2 26 43 PM" src="https://github.com/webpy/webpy/assets/82178/e77f3fda-26f2-4ea3-8ff4-fe3bee6f960c">

(which, of course, wasn't there 14 years ago https://web.archive.org/web/20100325163912/https://docs.python.org/library/tokenize.html)
it may be unwise to continue to rely on that module.

It seems odd that it's trying to tokenize `'$back">&larr; Back to Index</a></p>\n'`, so the real issue might be earlier in the process, but I haven't looked at what it's trying to do.

**Comment by cclauss** [comment]
Above... The parse started with the sting `'<p><a href="$back">&larr; Back to Index</a></p>'`

**Comment by scottbarnes** [comment]
The template parser is reading through to certain characters (such as `$`), or to certain combinations of characters, and calling different functions on the component parts of the line, as it processes each line. That is how it ends up with unterminated string literals, as it may read to a `$` in the middle of a string and segment the string there.

https://github.com/webpy/webpy/blob/ed3e92cceb6ed870b224107ea653f48fa7fc2d0a/web/template.py#L203-L226

I think the 'better' fix would be to rewrite the parser, but that seemed more prone to introducing new errors (as well as being a significantly more work). That said, if what I have done is too much of a hack, I accept that the parser may require rewriting.

I think I goofed up a bit in my examples, as I _think_ I should have been using `'back">&larr; Back to Index</a></p>\n')` (without the leading `$`), rather than `$back">&larr; Back to Index</a></p>\n'` as the substring. However, whether web.py was including the `$` or not when it subdivided the template string, it comes to the same thing in terms of parsing, since the issue is the unmatched `"`:
```python
In [30]: file = io.StringIO('back">&larr; Back to Index</a></p>\n')

In [31]: for token in tokenize.generate_tokens(file.readline):
    ...:     print(token)
    ...: 
TokenInfo(type=1 (NAME), string='back', start=(1, 0), end=(1, 4), line='back">&larr; Back to Index</a></p>\n')
---------------------------------------------------------------------------
TokenError                                Traceback (most recent call last)
Cell In[31], line 1
----> 1 for token in tokenize.generate_tokens(file.readline):
      2     print(token)

File ~/.pyenv/versions/3.12.1/lib/python3.12/tokenize.py:543, in _generate_tokens_from_c_tokenizer(source, encoding, extra_tokens)
    541     raise e from None
    542 msg = _transform_msg(e.msg)
--> 543 raise TokenError(msg, (e.lineno, e.offset)) from None

TokenError: ('unterminated string literal (detected at line 1)', (1, 5))
```

This also happens for I think every use of the form, `attribute="$variable"`, because as the parser reads through the string and divides it to into components, it will inevitably create unterminated string literals in `read_node()`. See, e.g.:
```python
In [32]: read_node = Parser().read_node

In [33]: read_node('<img url="$url">')
Out[33]: (t'<img url="', '$url">')
```

When `read_node()` calls `read_expr()` on the strings that start with `$`, `read_expr()` attempts to use `tokenize.generate_tokens()` in `get_tokens()`. But that no longer works:
```
In [37]: file = io.StringIO('blah">')

In [38]: for token in tokenize.generate_tokens(file.readline):
    ...:     print(token)
    ...: 
TokenInfo(type=1 (NAME), string='blah', start=(1, 0), end=(1, 4), line='blah">')
---------------------------------------------------------------------------
TokenError                                Traceback (most recent call last)
Cell In[38], line 1
----> 1 for token in tokenize.generate_tokens(file.readline):
      2     print(token)

File ~/.pyenv/versions/3.12.1/lib/python3.12/tokenize.py:543, in _generate_tokens_from_c_tokenizer(source, encoding, extra_tokens)
    541     raise e from None
    542 msg = _transform_msg(e.msg)
--> 543 raise TokenError(msg, (e.lineno, e.offset)) from None

TokenError: ('unterminated string literal (detected at line 1)', (1, 5))
```

**Comment by tfmorris** [comment]
Yes, silly of me to comment before actually digging in. The template BNF has
https://github.com/webpy/webpy/blob/c4c8bb0cd01ca59d81e0b52e6c72f36e7b07e4c7/web/template.py#L27-L28

It looks like the desired behavior is to gobble up as much Python expression as possible and return the rest as text.

> I think I should have been using 'back">&larr; Back to Index</a></p>\n') (without the leading $), rather than $back">&larr; Back to Index</a></p>\n' as the substring.

I agree.

The previous behavior was to return an error token for the unterminated quote and then continue tokenizing. I assume the higher level caller ignored everything from error token on, so perhaps the contents don't matter.

I have some other comments, but I'll make them on the PR.
